"""Quad-first meshing subpackage.

Q0 exposes the frozen strict options contract.  Q1 adds the resident
mixed T3/Q4 state, the transactional journal, and the single-step
advancing-front driver that converts one front T3 pair into a Q4.
Q2 adds bounded deterministic front-edge Steiner-split recovery that
enables a Q4 where pure Q1 pairing yields none.  Q3a adds an opt-in
fourfold cross-field that only *ranks* the already-admissible front
candidates (unguided :func:`front_step` stays byte-compatible).
"""

from .options import QUAD_MESHING_OPTIONS_SCHEMA, QuadMeshingOptions
from .front import (
    FrontNoCandidate,
    FrontRejected,
    area2,
    body_edges,
    candidate_partners,
    classify,
    edge_key,
    find_source_cell,
    front_step,
    local_swap,
    make_quad,
)
from .validate import QuadQualityRejected
from .recovery import (
    DEFAULT_RECOVERY_RATIOS,
    AdvanceReport,
    Attempt,
    RecoveryExhausted,
    RecoveryRejected,
    SplitReport,
    edge_split_recover,
    recover_then_front_step,
)
from .guidance import (
    CrossFieldReport,
    GuidanceRejected,
    LowConfidenceError,
    NEAR_ZERO,
    build_cross_field,
    field_from_directions,
    four_of,
    front_step_guided,
    rank_bodies,
    reflect_x,
    rot2,
    score_body,
)

from .domain import PlanarQuadDomain
from .boundary import BoundaryStation, BoundaryStationKey, BoundaryStationRegistry
from .seed import PlanarQuadSeed, build_planar_quad_seed
from .transitions import (
    ParentReplacement,
    TransitionRejected,
    TransitionReport,
    closure,
    collision,
    spacing_change,
)

# Q4: representable count-system model + integer MCF reduction + worker adapter
from .count_model import CountInstance, CountRejected
from .count_mcf import (
    INT64_MAX,
    MCFRequest,
    MCFResponse,
    MCFEncoding,
    CountInfeasible,
    InvalidSolution,
    MCF_REQUEST_SCHEMA,
    MCF_RESPONSE_SCHEMA,
    NotSolvedUnexpected,
    SolveReport,
    build_request,
    decode_response,
    tie_value,
    validate_response,
)
from .quad_mcf_worker import (
    WorkerCrash,
    WorkerLifecycle,
    WorkerMalformed,
    WorkerNotFound,
    WorkerTimeout,
    find_worker,
    run_worker,
    solve_count_instance,
)

# Q5: local TinyAD re-optimisation of free interior Q4-patch nodes
from .patch_energy import (
    Eps,
    Q5_REQUEST_SCHEMA,
    Q5_RESPONSE_SCHEMA,
    PatchRejected,
    PatchSpec,
    Q5SolveReport,
    InvalidSolutionQ4Patch,
    ObjectiveRegression,
    SolutionOutsideBox,
    WorkerErrorQ5,
    norm_axis,
    unit_axis,
    energy,
    size_term,
    align_term,
    shape_term,
    jacobian_term,
    is_valid_patch,
    quad_valid_dets,
    fd_gradient,
    fd_gradient_all,
    energy_and_gradient_fd,
    decode_q5_response,
)
from .quad_tinyad_worker import (
    WorkerLifecycleQ5,
    WorkerNotFoundQ5,
    WorkerCrashQ5,
    WorkerTimeoutQ5,
    WorkerMalformedQ5,
    default_worker_path,
    find_worker as find_q5_worker,
    run_worker as run_q5_worker,
    solve_q5_patch,
)

__all__ = [
    "QuadQualityRejected",
    "QUAD_MESHING_OPTIONS_SCHEMA",
    "QuadMeshingOptions",
    "FrontNoCandidate",
    "FrontRejected",
    "area2",
    "body_edges",
    "candidate_partners",
    "classify",
    "edge_key",
    "find_source_cell",
    "front_step",
    "local_swap",
    "make_quad",
    "DEFAULT_RECOVERY_RATIOS",
    "AdvanceReport",
    "Attempt",
    "RecoveryExhausted",
    "RecoveryRejected",
    "SplitReport",
    "edge_split_recover",
    "recover_then_front_step",
    "CrossFieldReport",
    "GuidanceRejected",
    "LowConfidenceError",
    "NEAR_ZERO",
    "build_cross_field",
    "field_from_directions",
    "four_of",
    "front_step_guided",
    "rank_bodies",
    "reflect_x",
    "rot2",
    "score_body",
    "TransitionRejected",
    "ParentReplacement",
    "TransitionReport",
    "spacing_change",
    "collision",
    "closure",
    # Q4
    "CountInstance",
    "CountRejected",
    "INT64_MAX",
    "MCFRequest",
    "MCFResponse",
    "MCFEncoding",
    "CountInfeasible",
    "InvalidSolution",
    "MCF_REQUEST_SCHEMA",
    "MCF_RESPONSE_SCHEMA",
    "NotSolvedUnexpected",
    "SolveReport",
    "build_request",
    "decode_response",
    "tie_value",
    "validate_response",
    "WorkerCrash",
    "WorkerLifecycle",
    "WorkerMalformed",
    "WorkerNotFound",
    "WorkerTimeout",
    "find_worker",
    "run_worker",
    "solve_count_instance",
    # Q5
    "Eps",
    "Q5_REQUEST_SCHEMA",
    "Q5_RESPONSE_SCHEMA",
    "PatchRejected",
    "PatchSpec",
    "Q5SolveReport",
    "InvalidSolutionQ4Patch",
    "ObjectiveRegression",
    "SolutionOutsideBox",
    "WorkerErrorQ5",
    "norm_axis",
    "unit_axis",
    "energy",
    "size_term",
    "align_term",
    "shape_term",
    "jacobian_term",
    "is_valid_patch",
    "quad_valid_dets",
    "fd_gradient",
    "fd_gradient_all",
    "energy_and_gradient_fd",
    "decode_q5_response",
    "WorkerLifecycleQ5",
    "WorkerNotFoundQ5",
    "WorkerCrashQ5",
    "WorkerTimeoutQ5",
    "WorkerMalformedQ5",
    "default_worker_path",
    "find_q5_worker",
    "run_q5_worker",
    "solve_q5_patch",
    # planar production PQ2
    "PlanarQuadDomain",
    "BoundaryStation",
    "BoundaryStationKey",
    "BoundaryStationRegistry",
    "PlanarQuadSeed",
    "build_planar_quad_seed",
]
